# Generated by Django 6.0.3 on 2026-03-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrderEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('piece_type', models.CharField(choices=[('ring', 'Ring'), ('necklace', 'Necklace / Chain'), ('bracelet', 'Bracelet / Bangle'), ('earrings', 'Earrings'), ('pendant', 'Pendant'), ('set', 'Jewellery Set'), ('other', 'Other')], max_length=20)),
                ('metal', models.CharField(choices=[('gold_22ct', '22ct Gold'), ('gold_18ct', '18ct Gold'), ('gold_24ct', '24ct Gold'), ('white_gold', 'White Gold'), ('rose_gold', 'Rose Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('unsure', 'Not sure — advise me')], max_length=20)),
                ('budget', models.CharField(choices=[('under_500', 'Under £500'), ('500_1000', '£500 – £1,000'), ('1000_2500', '£1,000 – £2,500'), ('2500_5000', '£2,500 – £5,000'), ('over_5000', 'Over £5,000'), ('flexible', 'Flexible / Not sure')], max_length=20)),
                ('description', models.TextField()),
                ('occasion', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_discussion', 'In Discussion'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('in_production', 'In Production'), ('completed', 'Completed'), ('declined', 'Declined')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Order Enquiry',
                'verbose_name_plural': 'Custom Order Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
