# Generated by Django 6.0.3 on 2026-03-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cash', 'Cash on Collection'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
