[deploy]
startCommand = "cd backend && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --access-logfile=- --log-level=debug --workers=2"
buildCommand = "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput"
