# Generated by Django 6.0.3 on 2026-03-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_hi',
            field=models.TextField(blank=True, verbose_name='Description (Hindi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pa',
            field=models.TextField(blank=True, verbose_name='Description (Punjabi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (Hindi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (Punjabi)'),
        ),
    ]
