# Generated by Django 6.0.3 on 2026-03-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_hi_product_description_pa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='making_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed making/labour charge added before VAT (£)', max_digits=8),
        ),
    ]
