# Generated by Django 6.0.3 on 2026-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldBuyback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('item_type', models.CharField(choices=[('jewellery', 'Jewellery'), ('coins', 'Gold Coins / Bars'), ('scrap', 'Scrap Gold'), ('watches', 'Watches'), ('other', 'Other')], max_length=20)),
                ('purity', models.CharField(choices=[('24ct', '24ct (999)'), ('22ct', '22ct (916)'), ('18ct', '18ct (750)'), ('14ct', '14ct (585)'), ('9ct', '9ct (375)'), ('unknown', 'Not Sure')], max_length=10)),
                ('estimated_weight', models.CharField(blank=True, help_text='e.g. "10g" or "approx 2 tola"', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the items')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('declined', 'Declined')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gold Buyback Request',
                'verbose_name_plural': 'Gold Buyback Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
